zuul:
  prefix: /api
  routes:
    voucherservice:
      path: /voucher/**
      serviceId: voucherservice

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    instance:
      hostname: localhost

server:
  port: 8079

spring:
  application:
    name: zuulservice

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000 #10 seconds

