zuul:
  prefix: /api
  routes:
    voucherservice:
      path: /voucher/**
#      serviceId: VOUCHER-SERVICE
      url: http://192.168.43.184:5000
    userservice:
      path: /user/**
#      serviceId: USERSERVICE
      url: http://192.168.43.55:8085
    auditservice:
      path: /log/**
#      serviceId: AUDITTRAIL
      url: http://192.168.43.55:8087

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.22.23.86:8070/eureka/
    instance:
      hostname: localhost

server:
  port: 8079

spring:
  application:
    name: zuul-service

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


